export const PROGRAMS = [
  "Software Engineering",
  "Computer Science",
  "Computer Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Mechanical Engineering",
  "Space Engineering",
  "Digital Media",
  "Data Science",
  "Information Technology",
  "Information Technology - BCom",
  "Mathematics",
  "Applied Mathematics",
  "Statistics",
  "Physics and Astronomy",
  "Biology",
  "Biomedical Science",
  "Biochemistry",
  "Chemistry",
  "Environmental Science",
  "Psychology",
  "Neuroscience",
  "Kinesiology and Health Science",
  "Nursing",
  "Global Health",
  "Health Studies",
  "Business Administration",
  "Commerce",
  "Economics",
  "Financial and Business Economics",
  "Accounting",
  "Finance",
  "Marketing",
  "Human Resources Management",
  "Business and Society",
  "Communication and Media Studies",
  "Design",
  "Film Production",
  "Media Arts",
  "Music",
  "Theatre",
  "English",
  "History",
  "Philosophy",
  "Political Science",
  "Sociology",
  "Law and Society",
  "Criminology",
  "Geography",
  "Environmental Studies",
  "International Development Studies",
  "Public Administration",
  "Other",
];
